language: csharp
mono: none
sudo: required
dist: xenial
dotnet: 2.2
script:
  - cd Hqub.MusicBrainz
  - dotnet restore
  - dotnet build -c Release
  - dotnet test Hqub.MusicBrainz.API.Test/Hqub.MusicBrainz.API.Test.csproj
global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
    - DOTNET_CLI_TELEMETRY_OPTOUT=1